name = "InformationGeometry"
uuid = "ee9d1287-bbdf-432c-9920-c447cf97a828"
authors = ["Rafael Arutjunjan"]
version = "1.15.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BoundaryValueDiffEq = "764a87c0-6b3e-53db-9096-fe964310641d"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
DerivableFunctionsBase = "2a74400c-0885-457e-a858-e4f63fac11e2"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DistributionsAD = "ced4e74d-a319-5a8a-b0ac-84af2272839c"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
LibGEOS = "a90b1aa1-3769-5649-ba7e-abc5a9d163eb"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SnoopPrecompile = "66db9d55-30c0-4569-8b51-7e840670fc0c"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
TreeViews = "a2a6695c-b41b-5b7d-aed9-dbfdeacea5d7"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[compat]
BenchmarkTools = "0.5, 0.6, 0.7, 1"
BoundaryValueDiffEq = "2, 3, 4, 5"
ColorSchemes = "2, 3"
Combinatorics = "1"
ComponentArrays = "0.13, 0.14, 0.15"
DataFrames = "0.20, 0.21, 0.22, 1"
DataInterpolations = "3, 4, 5, 6"
DerivableFunctionsBase = "0.1"
DiffEqCallbacks = "2, 3, 4"
Distributions = "0.21, 0.22, 0.23, 0.24, 0.25"
DistributionsAD = "0.5, 0.6"
ForwardDiff = "0.10"
HCubature = "1.4"
LibGEOS = "0.6, 0.7, 0.8, 0.9"
LineSearches = "5, 6, 7"
LsqFit = "0.9, 0.10, 0.11, 0.12, 0.13, 0.14, 0.15"
Measurements = "2"
ModelingToolkit = "5 - 9"
Optim = "1"
Optimization = "3, 4"
OrdinaryDiffEq = "5, 6"
PlotUtils = "1.0.9 - 1.1, 1.2"
PrettyTables = "1, 2"
ProgressMeter = "1.5, 1.6, 1.7"
RecipesBase = "1"
Roots = "1, 2"
SciMLBase = "1, 2"
SnoopPrecompile = "1"
Sobol = "1.3, 1.4"
SpecialFunctions = "0.9, 0.10, 1, 2"
StaticArrays = "0.11, 0.12, 1"
Suppressor = "0.1, 0.2"
SymbolicUtils = "0.11.3 - 0.17, 0.18, 0.19, 0.20, 1, 2 - 9"
Symbolics = "1 - 6"
TreeViews = "0.3"
Tullio = "0.3"
julia = "1"

[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Plots", "SafeTestsets", "Test"]
