name = "InformationGeometry"
uuid = "ee9d1287-bbdf-432c-9920-c447cf97a828"
version = "1.28.2"
authors = ["Rafael Arutjunjan"]

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
DerivableFunctionsBase = "2a74400c-0885-457e-a858-e4f63fac11e2"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DistributionsAD = "ced4e74d-a319-5a8a-b0ac-84af2272839c"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OptimizationBase = "bca83a33-5cc9-4baa-983d-23429ab6bcbb"
OrdinaryDiffEqCore = "bbf590c4-e513-4bbe-9b18-05decba2e5d8"
OrdinaryDiffEqLowOrderRK = "1344f307-1e59-4825-a18e-ace9aa3fa4c6"
OrdinaryDiffEqRosenbrock = "43230ef6-c299-4910-a778-202eb28ce4ce"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
OrdinaryDiffEqVerner = "79d7bb75-1356-48c1-b8c0-6832512096c2"
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"
PreallocationTools = "d236fae5-4411-538c-8e31-a6e3d9e00b46"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SnoopPrecompile = "66db9d55-30c0-4569-8b51-7e840670fc0c"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[weakdeps]
BoundaryValueDiffEqShooting = "ed55bfe0-3725-4db6-871e-a1dc9f42a757"
DelayDiffEq = "bcd4f6db-9728-5f36-b5f7-82caef46ccdb"
LibGEOS = "a90b1aa1-3769-5649-ba7e-abc5a9d163eb"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
ModelingToolkitBase = "7771a370-6774-4173-bd38-47e70ca0b839"
PEtab = "48d54b35-e43e-4a66-a5a1-dde6b987cf69"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"

[extensions]
InformationGeometryBoundaryValueDiffEqExt = ["BoundaryValueDiffEqShooting"]
InformationGeometryDelayDiffEqExt = ["DelayDiffEq"]
InformationGeometryLibGEOSExt = ["LibGEOS"]
InformationGeometryLsqFitExt = ["LsqFit"]
InformationGeometryLuxExt = ["Lux"]
InformationGeometryMakieExt = ["Makie"]
InformationGeometryModelingToolkitBaseExt = ["ModelingToolkitBase"]
InformationGeometryPEtabExt = ["PEtab", "ModelingToolkitBase"]
InformationGeometryStochasticDiffEqExt = ["StochasticDiffEq", "SciMLSensitivity"]

[compat]
ADTypes = "1"
BenchmarkTools = "0.5, 0.6, 0.7, 1"
BoundaryValueDiffEqShooting = "1"
Combinatorics = "1"
ComponentArrays = "0.13, 0.14, 0.15"
DataFrames = "0.20, 0.21, 0.22, 1"
DataInterpolations = "3, 4, 5, 6, 7, 8"
DelayDiffEq = "4, 5"
DerivableFunctionsBase = "0.1, 0.2"
DiffEqCallbacks = "2, 3, 4"
Distributions = "0.21, 0.22, 0.23, 0.24, 0.25"
DistributionsAD = "0.5, 0.6"
FillArrays = "1"
ForwardDiff = "0.10, 1"
GenericLinearAlgebra = "0.3"
HCubature = "1.4, 1.5, 1.6, 1.7"
LibGEOS = "0.6, 0.7, 0.8, 0.9"
LineSearches = "5, 6, 7"
LsqFit = "0.9 - 0.15"
Lux = "1"
Makie = "0.23, 0.24"
Measurements = "2"
ModelingToolkit = "11"
ModelingToolkitBase = "1"
Optim = "1, 2"
OptimizationBase = "2, 3, 4"
OrdinaryDiffEqCore = "1, 2, 3"
OrdinaryDiffEqLowOrderRK = "1"
OrdinaryDiffEqRosenbrock = "1"
OrdinaryDiffEqTsit5 = "1"
OrdinaryDiffEqVerner = "1"
PEtab = "4"
PlotUtils = "1.1, 1.2"
PreallocationTools = "0.4, 1"
PrettyTables = "3"
ProgressMeter = "1.5, 1.6, 1.7"
RecipesBase = "1"
RecursiveArrayTools = "3"
Roots = "1, 2"
SciMLBase = "1, 2"
SciMLSensitivity = "6, 7"
SnoopPrecompile = "1"
Sobol = "1.3, 1.4"
SpecialFunctions = "0.9, 0.10, 1, 2"
StaticArrays = "0.11, 0.12, 1"
StochasticDiffEq = "5, 6"
Suppressor = "0.1, 0.2"
SymbolicUtils = "1, 2, 3, 4"
Symbolics = "1 - 6, 7"
Tullio = "0.3"
julia = "1.10"

[extras]
BoundaryValueDiffEq = "764a87c0-6b3e-53db-9096-fe964310641d"
DelayDiffEq = "bcd4f6db-9728-5f36-b5f7-82caef46ccdb"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationNLopt = "4e6fcdb7-1186-4e1f-a706-475e75c168bb"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["BoundaryValueDiffEq", "DelayDiffEq", "FiniteDifferences", "LsqFit", "ModelingToolkit", "OrdinaryDiffEq", "Optimization", "OptimizationNLopt", "Plots", "SafeTestsets", "SciMLSensitivity", "StochasticDiffEq", "Test", "Zygote"]
